### ISSUE TITLE
Application quits after starting the service

### ISSUE THREAD

**Issue by olderuberbruns** [uberbruns/HomeMenuCE#1]
Host: OSX 10.13.6
Application: v0.0.2-alpha1

After pressing the button "start" in HomeMenu Preferences the application is closed. It is not executable anymore. Work around: launch a previous version of the app and stop the service.
[issue#1_CrashLog_2019-09-18_204907.txt](https://github.com/uberbruns/HomeMenuCE/files/3627903/issue.1_CrashLog_2019-09-18_204907.txt)

**Comment by uberbruns** [comment]
Please try the most recent version. I added a Crash Reporter. I hope it gets the chance to upload the report.

**Comment by uberbruns** [comment]
Fixed
